version: "3"
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre

  app:
    build: ./app
    depends_on:
      - postgres
    environment:
        TZ: "Asia/Tokyo"
    command:
      tail -f /dev/null
    volumes:
        - ./:/workspace